acc: 1
checks:
  concat_datasets: 0
  trials_vs_cont: 0
combine: 1
complete_model: 0
debug:
  active: 0
  dummy_data: 1
  log: 0
  reduce_channels: 30
  short: 0
dist: 1
downsample_rate: 20
figures:
  fig_1: 0
  make_all: 0
filters:
  alphabeta: 0
  bbhg: 0
  delta: 1
force: 1
learn:
  cv:
    gridsearch: false
    inner_folds: 4
    n_repeats: 1
    outer_folds: 5
  data:
    min_n_windows: 1
  fs:
    dim_reduction: 1
    greedy_forward: 0
    kbest: 0
    n_dims: 30
    random: false
    task_corr: 1
  psid:
    i:
    - 5
    - 10
    - 25
    - 50
    n1:
    - 3
    - 5
    - 10
    - 20
    - 30
    nx: []
  save: 1
  save_path: ./results/
missing_values:
  min_windows_to_incl_set: 5
  xyz_samples_for_gaps: 4
n_random_samples: 10
parallel: 1
plot: 0
pos: 1
random: 0
rereferencing:
  common_electrode_reference: 1
  laplacian: 0
save: 1
speed: 1
target_vector: 0
timeshift: 0
vel: 1
window:
  go: 1
  length: 300
  shift: 50
