checks:
  concat_datasets: 0
  trials_vs_cont: 0
combine: 0

learn:

  save: 1
  save_path: ./results/

  psid:
    i: [50]
    n1: [10]
    nx: []

  data:
    min_n_windows: 5

  cv:
    gridsearch: false
    inner_folds: 4
    outer_folds: 5
    n_repeats: 1
  
  fs:
    dim_reduction: 1
    n_dims: 30
    greedy_forward: 0
    kbest: 1
    random: false
    
debug:
  go: 0
  short: 0
  dummy_data: 1
  reduce_channels: 0  # broken
  log: 0

figures:
  make_all: 1
  fig_1: 0

missing_values:
  xyz_samples_for_gaps: 4
  min_windows_to_incl_set: 2

n_random_samples: 10
plot: 1

# Preprocessing
bands:
  lfc:
    - 0.1
    - 5
  beta:
    - 12
    - 30
  # hg:
  #   - 55
  #   - 95

window:
  go: 1
  length: 300
  shift: 50

random: 0
save: 1

# Hand kinematics
pos: 0
vel: 0
speed: 1

complete_model: 0

timeshift: 0  # ms
