checks:
  concat_datasets: 0
  trials_vs_cont: 0
combine: 1

learn:

  save: 1
  save_path: ./results/

  psid:
    i: 10
    n1: 50
    nx: 50

  data:
    min_n_windows: 5

  cv:
    gridsearch: false
    inner_folds: 4
    outer_folds: 5
    n_repeats: 1
  
  fs:
    dim_reduction: False
    n_dims: 50
    greedy_forward: 0
    kbest: 1
    random: false
    
debug: 0
debug_log: 0

figures:
  make_all: 1
  fig_1: 0
missing_values:
  xyz_samples_for_gaps: 4

n_random_samples: 10
plot: 1

# Preprocessing
bands:
  hfo:
  - 52
  - 200
  lfo:
  - 2
  - 48
  uhfo:
  - 200
  - 500
window:
  length: 300
  shift: 50

random: 0
save: 1

velocity: 0
