combine: 1
parallel: 1

filters:
  delta: 1        # Filter
  alphabeta: 0    # Filter + hilbert
  bbhg: 0         # Filter + hilbert

rereferencing:
  common_electrode_reference: 1
  laplacian: 0

target_vector: 0



checks:
  concat_datasets: 0
  trials_vs_cont: 0

learn:

  save: 1
  save_path: ./results/

  psid:
    i: [5, 10, 25, 50] #, 100]
    n1: [3, 5, 10, 20, 30]
    nx: []

  data:
    min_n_windows: 1

  cv:
    gridsearch: false
    inner_folds: 4 
    outer_folds: 5
    n_repeats: 1
  
  fs:
    dim_reduction: 1
    n_dims: 30
    task_corr: 1
    greedy_forward: 0
    kbest: 0

    random: false
  

downsample_rate: 20

debug:
  active: 0  # Rename active
  short: 0
  dummy_data: 1
  reduce_channels: 30  # incl in dummy data
  log: 0

figures:
  make_all: 0
  fig_1: 0

missing_values:
  xyz_samples_for_gaps: 4
  min_windows_to_incl_set: 5

n_random_samples: 10
plot: 0


window:
  go: 1
  length: 300
  shift: 50

random: 0
save: 1

# Hand kinematics
pos: 1
vel: 1
acc: 1
dist: 1
speed: 1
force: 1

complete_model: 0

timeshift: 0  # ms
